FROM golang:1.25-alpine

WORKDIR /app

# Install air
RUN go install github.com/air-verse/air@latest

COPY go.mod ./
RUN go mod download

COPY . .

EXPOSE 8080

# Jalankan air, bukan binary langsung
CMD ["air", "-c", ".air.toml"]

# Dockerfile ini untuk development, menggunakan air untuk hot reload